#ifndef _SMARTCALCV2_SRC_APP_MODEL_ADITIONAL_CLASES_ASSOCIATIVITY_H_
#define _SMARTCALCV2_SRC_APP_MODEL_ADITIONAL_CLASES_ASSOCIATIVITY_H_

enum Associativity {
  kNone,
  kLeft,
  kRight,
};

#endif  //_SMARTCALCV2_SRC_APP_MODEL_ADITIONAL_CLASES_ASSOCIATIVITY_H_