#ifndef _SMARTCALCV2_SRC_APP_MODEL_ADITIONAL_CLASES_PERCEDENCE_H_
#define _SMARTCALCV2_SRC_APP_MODEL_ADITIONAL_CLASES_PERCEDENCE_H_

enum Percedence {
  kDefault,
  kLow,
  kMedium,
  kHigh,
  kFunction,
  kUnaryMinus,
};

#endif  //_SMARTCALCV2_SRC_APP_MODEL_ADITIONAL_CLASES_PERCEDENCE_H_